import { Geist, Geist_Mono, Lato, Titillium_Web } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from 'next-themes' 

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const titilliumWeb = Titillium_Web({
  variable: "--font-titillium-web",
  subsets: ["latin"],
  weight: '400',
});

const lato = Lato({
  variable: "--font-lato",
  subsets: ["latin"],
  weight: '400',
});


export const metadata = {
  title: "Bayanno.ai",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${lato.variable} antialiased`}
      >
        <ThemeProvider attribute="class">
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
